### ISSUE TITLE
How to run the script after cloning the repository?

### ISSUE THREAD

**Issue by mahmoud2592** [bhavesh95863/whitelabel#1]
How to run the script after cloning the repository?
![error](https://user-images.githubusercontent.com/6003905/115694700-682f0800-a361-11eb-8405-eca7942c9ef3.png)

**Comment by bhavesh95863** [comment]
You need to follow this step.
1. bench get-app https://github.com/bhavesh95863/whitelabel
2. bench --site sitename install-app whitelabel

**Comment by bhavesh95863** [comment]
> How to run the script after cloning the repository?
> ![error](https://user-images.githubusercontent.com/6003905/115694700-682f0800-a361-11eb-8405-eca7942c9ef3.png)

You should have frappe-bench setup available in your system then only this app will work.

once you setup frappe-bench follow above mention step will work
