### ISSUE TITLE
Undo few changes done by app & upload logo

### ISSUE THREAD

**Issue by adityabagarka** [bhavesh95863/whitelabel#2]
How do i not make below changes

- Hide Help Menu
- Update onboard steps for remove video and documentation link(Version13)

Also where do i upload the logo to replace the login page image & the brand icon on the desk Navbar

**Comment by bhavesh95863** [comment]
I did not anything for that but I will add that in the setting so the user can ignore it.

**Comment by bhavesh95863** [comment]
We added a setting to ignore onboard steps and show the help menu.
