### ISSUE TITLE
If it can be site specific , will be extremely helpful 

### ISSUE THREAD

**Issue by chechani** [bhavesh95863/whitelabel#4]
If it can be site specific , will be extremely helpful

**Comment by bhavesh95863** [comment]
It's already site-specific @chechani.

**Comment by chechani** [comment]
I tried in one bench, but the logo changed refected in all sites of the bench

**Comment by bhavesh95863** [comment]
Maybe a cache issue. Try in a private window.

Because In frappe if you install one app in one site will not reflect anything in other sites.

**Comment by chechani** [comment]
We uploaded logo at this address  as advised /home/frappe/frappe-bench/apps/whitelabel/whitelabel/public/images. So its app common folder and hence same logo visible in two sites

**Comment by bhavesh95863** [comment]
@chechani but if you install that app on a particular site then only it will use the logo from that mentioned path else it will fetch from erpnext default logo.

This feature by default available in the frappe framework it self so i believe you have some cache issue.
