### ISSUE TITLE
Disable after login popup, if New update are available

### ISSUE THREAD

**Issue by smthakor1979** [bhavesh95863/whitelabel#5]
![image](https://user-images.githubusercontent.com/66081909/115920267-944ca500-a497-11eb-923e-97349d7b66a2.png)

Some time non technical user doesnt have any idea and assume that they are requested to update by admin and then click on it.

Popup should come only if user is "Adminitrator" .

**Comment by bhavesh95863** [comment]
That popup only comes to that user which has a system manager role but I will add a setting for this to ignore this popup for all roles.

**Comment by bhavesh95863** [comment]
@smthakor1979  we added a setting in the Whitelabel setting page to ignore that popup.
