### ISSUE TITLE
NameError: name '_' is not defined after update 

### ISSUE THREAD

**Issue by chechani** [bhavesh95863/whitelabel#8]
After the update, an error message coming as, "NameError: name '_' is not defined after update ". The message went if we uninstall the Whitelabel app. If it is related to defining name in Whitelabel Setting, we changed and it reflected on the login screen

![image](https://user-images.githubusercontent.com/6291292/117382679-b06f2e00-aefc-11eb-85fa-0b37b54dc50f.png)

**Comment by bhavesh95863** [comment]
@chechani thanks for reporting issue.

**Comment by bhavesh95863** [comment]
Issue resolved.

**Comment by chechani** [comment]
It solved
