### ISSUE TITLE
Setting for login applied and not applied too 

### ISSUE THREAD

**Issue by chechani** [bhavesh95863/whitelabel#9]
Strange behavior applied somewhere and somewhere not even after clearing local cache and website cache.

**Comment by bhavesh95863** [comment]
@chechani I think the issue with your setup. I am using this app with my 5-6 servers that are multitenant and the app is working fine there.

**Comment by chechani** [comment]
It worked in general but could not identify the issue for one set up so raised the issue. Thx

**Comment by chechani** [comment]
thx
